### PR TITLE
Feature/savings target update and save

### PR DESCRIPTION
**Pull request by VilmaIkonen**

### CODE REVIEW

**Comment by khushboogoyal88** [comment]
if you just do ....... saving: parseFloat(e.target[0].value) on line 36 on LandingPage.js, It will remove zeros from input value, e.g. if user enters 0100, it will take 100.

**Review by vesasuikkola — DISMISSED** [review]
Khushboo's suggestion is good, I think; beyond that I don't have any other comments.

**Review by khushboogoyal88 — APPROVED** [review]
Looks good to me.

**Review by khushboogoyal88 — DISMISSED** [review]
Looks good to me.

**Review by risman — DISMISSED** [review]

**Review by vesasuikkola — APPROVED** [review]

**Review by risman — APPROVED** [review]

**Pull request merged**
