### PR TITLE
Bugfix/frontend skeleton/component structure

### PR DESCRIPTION
**Pull request by vesasuikkola**

### CODE REVIEW

**Comment by khushboogoyal88** [comment]
Hi, Can we change the expense page styling a bit, the category list, seema unreadable at the moment, If we increase its weightge, and make it conatin half the width or maore, it would be better readable, Alternatively, we can also, reduce the font size, for better readability.

**Comment by khushboogoyal88** [comment]
Also, Save button styling is different from the design.

**Comment by khushboogoyal88** [comment]
Also, I think it was a great decision to put everything in App.css and AppHeader.css :)

**Comment by khushboogoyal88** [comment]
Should we also change the name of ExpenseList component to Addexpenses...??? It is more descriptive.!

**Comment by vesasuikkola** [comment]
> Hi, Can we change the expense page styling a bit, the category list, seema unreadable at the moment, If we increase its weightge, and make it conatin half the width or maore, it would be better readable, Alternatively, we can also, reduce the font size, for better readability.

At the moment, the dropdown itself will auto-adjust to the dropdown option list, like so:
image

This will not work for very long category names, but I'm not sure how to affect e.g. wrapping here. I raised the issue a new PBI.

**Comment by vesasuikkola** [comment]
> Also, Save button styling is different from the design.

Yes, I did that on purpose to unify the button styling. Let's discuss during demo if we want to change this further in the next sprint.

**Comment by vesasuikkola** [comment]
> Should we also change the name of ExpenseList component to Addexpenses...??? It is more descriptive.!

The way I'm looking at it, ExpenseList contains now two features - adding a new expense item and the list of added expense items itself. ExpenseList in that sense is more descriptive, imo. We could however refactor further to separate the input functionalities to a component of its own (which could be then used for every input - user name, salary, savings target, expense item). Let's discuss during next sprint planning if we want to do this. I raised a new PBI for this.

**Review by VilmaIkonen — CHANGES_REQUESTED** [review]
App.css: Why do we jump on headings from h3 to h6? perhaps not a good option from accessibility point of view.

**Comment by vesasuikkola** [comment]
> App.css: Why do we jump on headings from h3 to h6? perhaps not a good option from accessibility point of view.

I left h4-h5 open on purpose if some use case comes up for them later on. I used h6 now for the app copyright note and figured the lowest level of heading would be more appropriate for it.

**Review by VilmaIkonen — DISMISSED** [review]

**Review by VilmaIkonen — APPROVED** [review]

**Review by khushboogoyal88 — APPROVED** [review]
Looks good, working fine for me.

**Pull request merged**
